### ISSUE TITLE
No route matches [GET] "...cloudinary-jquery-file-upload.js.map"

### ISSUE THREAD

**Issue by benbartling** [cloudinary/cloudinary_gem#199] opened 2016-04-22 14:15 UTC
I'm using version 1.1.6 and I'm getting the following error when including the cloudinary JS via assets pipeline:

ActionController::RoutingError (No route matches [GET] "/assets/cloudinary/cloudinary-jquery-file-upload.js.map")

This is causing the direct upload functionality to break.

**Comment by elCorsaiR** [comment] 2016-04-26 10:16
I'm having the same error last days.

**Comment by djjimba** [comment] 2016-04-27 17:31
I get the same error but I'm getting away with using
gem 'cloudinary', '1.1.0'
which is not broken.

**Comment by elCorsaiR** [comment] 2016-04-28 06:40
My problem was that I used fileupload to init: 
`$(".cloudinary-fileupload").fileupload
      dropZone: "#photos"`
Solution:
`$(".cloudinary-fileupload").cloudinary_fileupload`

**Comment by blimey85** [comment] 2016-05-23 22:03
Typically what causes this is the main .js file including a call to the .map file. My functionality still works fine however I'm seeing the error all over in my logs.

**Comment by trautwein** [comment] 2016-05-31 12:28
Same problem here. The issue seems to have been introduced in version `1.1.3`.

Uploads don't work in any version from `1.1.3` to the current `1.1.6`. I haven't been able to track it down to anything specific except for the aforementioned `ActionController::RoutingError (No route matches [GET] "/assets/cloudinary/cloudinary-jquery-file-upload.js.map")`.

**Comment by tocker** [comment] 2016-06-01 07:04
The issue is a result of a change to [Cloudinary's JavaScript library](https://github.com/cloudinary/cloudinary_js). Due to compatibility issues with some environments, the script no longer autonomously calls `cloudinary_fileupload()`. Instead you have to call it explicitly.

BTW `cloudinary_fileupload()` internally [calls](https://github.com/cloudinary/cloudinary_js/blob/2.0.8/src/jquery-file-upload.coffee#L53) Blueimp's `fileupload()` so there's no need to call both.

Sorry for the unintentional outcome. We will update the documentation to reflect this change.

**Comment by blimey85** [comment] 2016-06-01 07:37
How do we resolve the .map file not being included and thus causing the log to be flooded with routing errors? I saw at the bottom of the .js file where it's linking to the .js.map file but no idea how to override that.

**Comment by tocker** [comment] 2016-06-06 12:12
Fixed in version 1.1.7. Please let us know if it solved your problem.

The issue was with the Cloudinary JavaScript library.The GEM fetches the `js` folder in that library for backward compatibility reasons. The `cloudinary-jquery-file-upload.js` file was renamed to `jquery.cloudinary.js`. However the comment added by the compiler pointed to a map file that was not included in the Gem. The Fix was to rename the source `cloudinary-jquery-file-upload.coffee` to `jquery.cloudinary.coffee` and only then compile it. The source and map files were added to the gem.

**Comment by trautwein** [comment] 2016-06-06 13:25
@tocker Works for us, thanks!

**Comment by blimey85** [comment] 2016-06-06 21:39
@tocker great work! Much appreciated.

**Closed** 2017-02-16 15:35 UTC
