### ISSUE TITLE
When specifying CLOUDINARY_URL gem should infer the API key and secret

### ISSUE THREAD

**Issue by callmeed** [cloudinary/cloudinary_gem#275] opened 2017-11-28 20:19 UTC
When using the CLOUDINARY_URL environment variable in a PaaS like Heroku, you shouldn't need to also set environment vars for the api key and secret, since they are part of the URL. 

However, some features (notably CarrierWave integration) will not work with the CLOUDINARY_URL alone set. A `CloudinaryException` will be raised.

**Comment by nadavofi** [comment] 2017-12-11 07:37
When first loaded, Cloudinary gem determines the global configuration based on the env-vars (e.g. `CLOUDINARY_URL` if present). Carrierwave integration is a subclass of Cloudinary gem, therefore this setup should work flawlessly. Could you please share a concrete example which reproduces this issue?

**Comment by roeeba** [comment] 2018-09-21 18:08
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2018-09-21 18:08 UTC
