### ISSUE TITLE
after carrierwave 1.0 upgrade, we can't upload any more

### ISSUE THREAD

**Issue by farukca** [cloudinary/cloudinary_gem#227] opened 2017-01-11 11:57 UTC
I am using cloudinary gem with version 1.3.0; and after carrierwave 1.0 upgrade, our uploaders can't upload pictures and files to cloudinary.

When we update out gemfile to use carrierwave with version '0.11.2', then our uploaders can upload files.

**Comment by taragano** [comment] 2017-01-11 22:24
I couldn't reproduce this issue on my end. Cloudinary's GEM v.1.3.0 and CarrierWave 1.0 seems to work successfully for me, both server-side and client-side uploads worked.
I was trying it on Ruby 2.1.5 and Rails 4.2.0. Can you please share some more about your environment? Have you tried making sure other included GEMs are also updated (`bundle install`) ?

**Comment by staugaard** [comment] 2017-02-04 18:35
There is definitely an issue where carrerwave will pass 2 arguments to `download!`:
https://github.com/carrierwaveuploader/carrierwave/blob/v1.0.0/lib/carrierwave/mounter.rb#L81

While cloudinary only expects one:
https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/carrier_wave/remote.rb#L2

**Comment by staugaard** [comment] 2017-02-04 18:36
I guess that is what was reported in #221

**Comment by taragano** [comment] 2017-02-06 20:46
Thank you for that. I've passed it on to our team.

**Comment by taragano** [comment] 2017-02-21 22:24
We've updated our GEM to ver. 1.5.1, which should [include a fix](https://github.com/cloudinary/cloudinary_gem/commit/dff66b90135fa524127db965dc368671afedc403) for this.
Can you please verify?

**Comment by josue** [comment] 2017-03-29 18:31
@taragano Thanks for suggestion, the issue gone now. I updated my Gemfile to:

```ruby
gem 'carrierwave', :git => 'https://github.com/carrierwaveuploader/carrierwave.git', :branch => 'master'
gem 'cloudinary', :git => 'https://github.com/cloudinary/cloudinary_gem.git', :branch => 'master'
```

**Comment by taragano** [comment] 2017-03-31 20:36
Thank you for confirming @josue.
I'll close this issue for now, but please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

**Closed by taragano** 2017-03-31 20:36 UTC
Labels: bug
