### ISSUE TITLE
undefined method `<<' for {:read_timeout=>60, :continue_timeout=>nil, :debug_output=>nil}:Hash Did you mean? <

### ISSUE THREAD

**Issue by lionel02218** [cloudinary/cloudinary_gem#258] opened 2017-05-25 09:25 UTC
My old rails version is 4.2, and now upgrade to 5.1.1.
I'm using cloudinary_gem in rails 5.1.1 project.
ruby version is 2.4.0
gem 'rails', '5.1.1'
...
gem 'cloudinary', '~> 1.8'

But just got as like image.
![screen shot 2017-05-25 at 5 23 15 pm](https://cloud.githubusercontent.com/assets/19420895/26444433/07e4cd66-416f-11e7-9384-c58e9ebf769b.png)

**Comment by roeeba** [comment] 2017-06-12 08:42
Hi @lionel02218, I apologise for the delayed response. Can you please share the entire code responsible for this error so we could try and reproduce it on our side as well?

**Comment by bunnymatic** [comment] 2017-09-11 06:08
Could it be an old version of webmock? https://github.com/bblimke/webmock/blob/master/CHANGELOG.md#231
I hit something similar upgrading to ruby 2.4.0.

**Comment by roeeba** [comment] 2017-10-10 11:16
Hi @bunnymatic. Sorry for the late reply. It's really hard to tell what is the source of the issue until we could reproduce it ourselves. If you still need our help, please share your code and we'll be happy to help further.

**Comment by roeeba** [comment] 2017-11-23 10:28
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2017-11-23 10:28 UTC
Labels: question
