### ISSUE TITLE
rake cloudinary:fetch_assets does not exist

### ISSUE THREAD

**Issue by JESii** [cloudinary/cloudinary_gem#308] opened 2018-06-10 18:03 UTC
Attempted the rake command from the documentation, but get error:
```
rake aborted!
Don't know how to build task 'cloudinary:fetch_assets' (see --tasks)
Did you mean?  cloudinary:sync_static
```
Running `rake --tasks` confirmed that this"fetch_assets" rake task does not exist.

cloudinary 1.8.1
rails 5.2.0
ruby 2.4.0p0

**Comment by taragano** [comment] 2018-06-14 18:14
I could reproduce it when I tried `rake cloudinary:fetch_assets` inside one of the sample projects. Note that it should be invoked from the GEM's root folder.
Please let me know if it works for you?

**Comment by taragano** [comment] 2018-07-18 20:02
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

**Closed by taragano** 2018-07-18 20:02 UTC
Labels: question
