### ISSUE TITLE
cloudinary.yml file not loading

### ISSUE THREAD

**Issue by bretweinraub** [cloudinary/cloudinary_gem#284] opened 2018-02-13 15:41 UTC
Downloaded via the management console, and installed into

     RAILS_ROOT/config/cloudinary.yml

I can see in the console that

     Cloudinary.config

has no data in it.

Note, using an initializer is working for me.

**Comment by roeeba** [comment] 2018-02-15 11:55
Hi @bretweinraub, could you please share your project with us, so we could try and reproduce this? if you want to keep it confidential, please feel free to open a support ticket and we'll continue from there.

**Comment by roeeba** [comment] 2018-03-13 08:27
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2018-03-13 08:27 UTC
Labels: question
