### ISSUE TITLE
remote_image_url is not working properly with inherited public_id method

### ISSUE THREAD

**Issue by harsh15** [cloudinary/cloudinary_gem#162] opened 2015-07-02 13:10 UTC
I have inherited the public_id method in my uploader.
public_id is getting called for normal image upload, but when I am trying to upload the image with remote_image_url = "some_image_url", then public_id method is not getting called. 

Can you figure out, Why public_id is not getting called while uploading image using remote_image_url.

**Comment by taragano** [comment] 2015-07-03 14:03
Hi, 
Unfortunately we couldn't reproduce this issue. 
Can you please share your uploader? Specifically how you overrode the `public_id` method?

**Comment by taragano** [comment] 2015-12-04 12:55
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by taragano** 2015-12-04 12:55 UTC
Labels: question
