### ISSUE TITLE
Ruby 2.5 and Rails 5

### ISSUE THREAD

**Issue by tbsvttr** [cloudinary/cloudinary_gem#296] opened 2018-03-14 14:28 UTC
Does this Gem work with Ruby 2.5 and Rails 5.1?

I ask because this page only mentions older versions of Ruby and Rails: https://cloudinary.com/documentation/rails_integration#ruby_gem_features

**Comment by shirlymanor** [comment] 2018-03-14 22:11
While we didn't test all the new Ruby versions in a formal way. we have customers who are using the new version of Ruby. I'm using Ruby 2.4.2 and Rails 4.2.7 and it's working just fine.

**Comment by tbsvttr** [comment] 2018-03-15 09:02
Okay. We will test and inform you if something does not work out.

**Comment by barrywoolgar** [comment] 2018-07-12 07:58
I am using Ruby 2.5.1 and Rails 5.1 in production and this gem appears to be working fine. I'm not using _all_ aspects of the gem but perhaps this issue can be closed as no actual bug is detailed here?

**Comment by cloudinaraz** [comment] 2018-07-12 11:54
@barrywoolgar thank you for your feedback!
As we still have several open issues with Rails 5, we are not formally supporting it yet.
However, you are correct in saying that this is not a bug. Therefore we've changed the label of the issue.

**Comment by TImPDaley** [comment] 2018-12-14 22:20
I just found an issue with Ruby 2.4 - Ruby deprecated NIL constant so  we get a warning:

> gems/cloudinary-1.11.0/lib/cloudinary/utils.rb:1074: warning: constant ::NIL is deprecated

I believe line 1074  - needs to be changed from NIL constant to nil
`  def self.process_custom_pre_function(param)
    value = process_custom_function(param)
    value ? "pre:#{value}" : NIL
  end`
 I am planning on doing a pull and testing then seeing if I can fix it and submit it.

**Comment by d-mendoza** [comment] 2018-12-18 19:50
@TImPDaley 
Thank you for reporting this. If you would like to offer a pull request to remove the warnings, please do. If not, we will address it soon here https://github.com/cloudinary/cloudinary_gem/issues/329

**Comment by TImPDaley** [comment] 2018-12-26 19:52
Looks like it was already finished before I could get to it... THANK YOU.
I will get it going faster next time.. Happy Holidays and Happy New Year!
My Best Regards!
Tim Daley
(248) 770-3125
www.linkedin.com/in/timdaley/

**Closed** 2022-02-07 22:14 UTC
Labels: enhancement
